services:
  db:
    image: postgres:15
    container_name: knowledge_db
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - knowledge_db:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine
    container_name: redis
    ports:
      - "6378:6379"

volumes:
  knowledge_db:
    driver: local