services:
  db:
    image: postgres:15
    container_name: knowledge_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - knowledge_db:/var/lib/postgresql/data

volumes:
  knowledge_db:
    driver: local