# Generated by Django 5.2 on 2025-04-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('permissions', models.ManyToManyField(to='workspaces.permission')),
            ],
            options={
                'db_table': 'workspace_roles',
            },
        ),
    ]
