# Generated by Django 5.2 on 2025-04-25 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_workspacemembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='workspace',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='workspaces.permission'),
        ),
    ]
