# Generated by Django 5.2 on 2025-04-25 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_role_workspace_alter_role_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['workspace', 'id']},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='codename',
            new_name='method_name',
        ),
        migrations.AddField(
            model_name='permission',
            name='depends_on',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='workspaces.permission'),
            preserve_default=False,
        ),
    ]
