# Generated by Django 5.2 on 2025-04-26 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_alter_role_options_alter_workspace_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workspaces.permission'),
        ),
    ]
