# Generated by Django 5.2 on 2025-04-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_alter_permission_depends_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='model',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permission',
            name='method_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('model', 'method_name')},
        ),
    ]
