# Generated by Django 5.2 on 2025-04-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_permission_model_alter_permission_method_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['model', 'id']},
        ),
    ]
